### PR TITLE
bump up the alias branch

### PR DESCRIPTION
**Pull request by cordoval**
Sent using [Gush](https://github.com/gushphp/gush)

### CODE REVIEW

**Comment by cordoval** [comment]
this is giving me a lot of problems with https://github.com/cordoval/matthew-7-12/pull/12/files

**Comment by cordoval** [comment]
```
~ php bldr.phar install                                                 Luiss-MacBook-Pro-3 [0:44:51]
Loading composer repositories with package information
Installing dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bldr-io/gush-block dev-master@dev -> satisfiable by bldr-io/gush-block[dev-master].
    - bldr-io/gush-block dev-master requires gushphp/gush ~1.8.3 -> satisfiable by gushphp/gush[1.8.3, 1.8.4].
    - gushphp/gush 1.8.3 requires herrera-io/version ~1.1.1 -> satisfiable by herrera-io/version[1.1.1].
    - gushphp/gush 1.8.4 requires herrera-io/version ~1.1.1 -> satisfiable by herrera-io/version[1.1.1].
    - Conclusion: don't install herrera-io/version 1.1.1
```

**Comment by cordoval** [comment]
:+1: please merge, i am totally stuck

**Comment by ghost** [comment]
Done, and thanks!

**Pull request merged**
