### PR TITLE
Add Version::__toString()

### LINKED ISSUE #2: Version::__toString()
I feel it would be beneficial to implement `__toString()` in Version, and to call that in `Dumper::toString()` - reason being I don't really want to care about displaying version numbers, I would just like to be able to `echo new Version(1, 0, 0);`.

Would this be acceptable? I'll gladly provide a PR. Thanks.

### PR DESCRIPTION
**Pull request by aderuwe**
Fixes #2

### CODE REVIEW

**Comment by ghost** [comment]
Please keep the work in `Dumper`, but have `Version::__toString()` call `Dumper`.

**Comment by aderuwe** [comment]
Done, and test added.

**Comment by aderuwe** [comment]
And rebased.

**Comment by ghost** [comment]
Thanks! I'll push out a new release shortly.

**Pull request merged**
