### PR TITLE
bumped up the branch alias

### PR DESCRIPTION
**Pull request by cordoval**

### CODE REVIEW

**Comment by ghost** [comment]
Why is the version number being bumped up?

**Comment by cordoval** [comment]
according to releases tab we are already in 1.1 which means the branch alias should be greater than or looking towards the future which is 1.2 or more reasonably 2.0. It works when i require ~1.0@dev however it is contradictory.

**Comment by cordoval** [comment]
for example https://github.com/FriendsOfSymfony/FOSRestBundle/pull/673#issuecomment-33316287, thanks to cc/ @lsmith77

**Comment by ghost** [comment]
I see what you mean, and it makes sense!

I decided to look towards Symfony as an example and found that they uses aliases such as `2.5.x-dev`.

Since a version `2.0` isn't in the works and I don't see myself release a 1.2 release soon, I'd rather change the dev branch alias to `1.1.x`.

If you could amend the PR to change the alias to `1.1.x`, I would be more than happy to accept it!

**Comment by cordoval** [comment]
ping @kherge

**Comment by ghost** [comment]
Thanks!

**Pull request merged**
